default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  username: shielded-savannah-89334
  database: shielded-savannah-89334_production
  password: <%= ENV['SHIELDED-SAVANNAH-89334_DATABASE_PASSWORD'] %>